# Generated by Django 3.0.8 on 2020-11-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201123_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='ownner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='ownner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='ownner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='ownner',
            new_name='owner',
        ),
    ]
