# Generated by Django 3.1.3 on 2020-12-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
    ]
